In [1]:
from algos.transformation import Transformation
from algos.clipping import Clipping
from algos.roberts import Roberts
import numpy as np

## Задание 1


In [2]:
# m - двигать
# r - поворот
# s - масштабировать
# fv - отразить по вертикали
# fh - отразить по горизонтали

points = [[1, 4], [4, 4], [4, 1], [1, 1]]
transfromations = ['m (-2.5 -2.5)', 'fv 1', 's (2/3 1)', 'm (9 7/2)']

result = Transformation.complex_transform2d(points, transfromations)
print(f'Старые точки: {result['old_points']}')
print(f'Новые точки: {result['new_points']}')
print(f'Матрица преобразования: {result['tr_matrix']}')

------------------------------
Фигура сдвинута на вектор: [Fraction(-5, 2), Fraction(-5, 2)]
Матрица сдвига: [[1 0 0]
 [0 1 0]
 [Fraction(-5, 2) Fraction(-5, 2) 1]]
Итоговая матрица преобразования: [[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [-2.5 -2.5 1.0]]
------------------------------
------------------------------
Фигура отражена по вертикали
Матрица отражения: [[-1  0  0]
 [ 0  1  0]
 [ 0  0  1]]
Итоговая матрица преобразования: [[-1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [2.5 -2.5 1.0]]
------------------------------
------------------------------
Фигура масштабирована в: [Fraction(2, 3), Fraction(1, 1)] раз
Матрица масшиабирования: [[Fraction(2, 3) 0 0]
 [0 Fraction(1, 1) 0]
 [0 0 1]]
Итоговая матрица преобразования: [[-0.6666666666666666 0.0 0.0]
 [0.0 1.0 0.0]
 [1.6666666666666665 -2.5 1.0]]
------------------------------
------------------------------
Фигура сдвинута на вектор: [Fraction(9, 1), Fraction(7, 2)]
Матрица сдвига: [[1 0 0]
 [0 1 0]
 [Fraction(9, 1) Fraction(7, 2) 1]]
Итоговая матрица пре

## Задание 2

### Доказать выпуклость


In [3]:
# Вершины выписывать по часовой стрелке
verts = [[1, 1], [3, 4], [9, 4], [7, 1]]
is_convex = Clipping.is_convex(verts)

Проверка многоугольника на выпуклость
------------------------------
Проверка векторов, образованных точками: [7, 1]-[1, 1] и [1, 1]-[3, 4]
Произведение векторов равно: -18k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [1, 1]-[3, 4] и [3, 4]-[9, 4]
Произведение векторов равно: -18k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [3, 4]-[9, 4] и [9, 4]-[7, 1]
Произведение векторов равно: -18k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [9, 4]-[7, 1] и [7, 1]-[1, 1]
Произведение векторов равно: -18k
Знак произведения веторов: отрицательный
------------------------------
Полигон выпуклый, внутренние нормали ориентированы вправо от его контура


### Найти внутренние нормали

In [4]:
print(f'Внутренние нормали: {Clipping.inner_normals(verts)}')

Поиск внутренних нормалей вектора
------------------------------
Нормаль для ребра из вершин: ([1, 1], [3, 4])
Получившаяся нормаль: (-3, 2), обращена вне полигона
После обращения внутрь: (3, -2)
------------------------------
------------------------------
Нормаль для ребра из вершин: ([3, 4], [9, 4])
Получившаяся нормаль: (0, 6), обращена вне полигона
После обращения внутрь: (0, -6)
------------------------------
------------------------------
Нормаль для ребра из вершин: ([9, 4], [7, 1])
Получившаяся нормаль: (3, -2), обращена вне полигона
После обращения внутрь: (-3, 2)
------------------------------
------------------------------
Нормаль для ребра из вершин: ([7, 1], [1, 1])
Получившаяся нормаль: (0, -6), обращена вне полигона
После обращения внутрь: (0, 6)
------------------------------
Внутренние нормали: [(3, -2), (0, -6), (-3, 2), (0, 6)]


### Если Кирус-Бэк

In [5]:
verts2 = [(1, 1), (3, 4), (9, 4), (7, 1)]
line = [(5, 7), (9, 1)]
print(f'Видимая часть отрезка: {Clipping.cyrus_beck(verts2, line)}')

Рёбра многоугольника: [((1, 1), (3, 4)), ((3, 4), (9, 4)), ((9, 4), (7, 1)), ((7, 1), (1, 1))]
Поиск внутренних нормалей вектора
------------------------------
Нормаль для ребра из вершин: ((1, 1), (3, 4))
Получившаяся нормаль: (-3, 2), обращена вне полигона
После обращения внутрь: (3, -2)
------------------------------
------------------------------
Нормаль для ребра из вершин: ((3, 4), (9, 4))
Получившаяся нормаль: (0, 6), обращена вне полигона
После обращения внутрь: (0, -6)
------------------------------
------------------------------
Нормаль для ребра из вершин: ((9, 4), (7, 1))
Получившаяся нормаль: (3, -2), обращена вне полигона
После обращения внутрь: (-3, 2)
------------------------------
------------------------------
Нормаль для ребра из вершин: ((7, 1), (1, 1))
Получившаяся нормаль: (0, -6), обращена вне полигона
После обращения внутрь: (0, 6)
------------------------------
------------------------------
Рассматриваемое ребро: ((1, 1), (3, 4))
Нормаль: (3, -2)
Для данного о

### Если Коуэн-Сазерленд

In [6]:
verts3 = [(1, 2), (6, 5)]
l1 = [(4, 6), (7, 3)]
l2 = [(0, 0), (7, 1)]
Clipping.cohen_sutherland(verts3, l1)

Код для первой точки линии: 1000
Код для второй точки линии: 0010
------------------------------
Отрезок нуждается в отсекании
Начальная точка лежит вне окна!
Рассматриваемая точка (4, 6) выше окна
Новая начальная точка: (5.0, 5)
------------------------------
------------------------------
Отрезок нуждается в отсекании
Конечная точка лежит вне окна!
Рассматриваемая точка (7, 3) справа от окна
Новая конечная точка: (6, 4.0)
------------------------------
Отсечённая линия лежит внутри окна
Линия отсечена, новые точки: (5.0, 5), (6, 4.0)


[(5.0, 5), (6, 4.0)]

## Задание 3

In [7]:
# Пример входных данных: массив массивов граней 3D
faces = [
    [(0, 0, 0), (0, 2, 0), (0, 0, 2)],
    [(0, 0, 0), (0, 2, 0), (2, 0, 0)],
    [(0, 0, 0), (0, 0, 2), (2, 0, 0)],
    [(0, 2, 0), (0, 0, 2), (2, 0, 0)],
]

faces_matrix = Roberts.generate_faces_matrix(faces)
V = faces_matrix.T
print("Матрица граней объекта:")
print(V)
P = np.array([0,0,1,0])
result = np.dot(P, V)

for index, element in enumerate(result):
    print(f'Граней {index+1}: {element}')

Матрица граней объекта:
[[ 4  0  0  4]
 [ 0  0  4  4]
 [ 0 -4  0  4]
 [ 0  0  0 -8]]
Граней 1: 0
Граней 2: -4
Граней 3: 0
Граней 4: 4
