In [1]:
from algos.transformation import Transformation
from algos.clipping import Clipping
from algos.roberts import Roberts
import numpy as np

## Задание 1


In [3]:
# m - двигать
# r - поворот
# s - масштабировать
# fv - отразить по вертикали
# fh - отразить по горизонтали

points = [[1, 4], [4, 4], [4, 1], [1, 1]]
transfromations = ['m (-2.5 -2.5)', 'r 90', 's (4/3 2/3)', 'm (8 4)']

result = Transformation.complex_transform2d(points, transfromations)
print(f'Старые точки: {result['old_points']}')
print(f'Новые точки: {result['new_points']}')
print(f'Матрица преобразования: {result['tr_matrix']}')

------------------------------
Фигура сдвинута на вектор: [Fraction(-5, 2), Fraction(-5, 2)]
Матрица сдвига: [[1 0 0]
 [0 1 0]
 [Fraction(-5, 2) Fraction(-5, 2) 1]]
Итоговая матрица преобразования: [[1.0 0.0 0.0]
 [0.0 1.0 0.0]
 [-2.5 -2.5 1.0]]
------------------------------
------------------------------
Фигура повёрнута на угол: [Fraction(90, 1)] градусов
Матрица поворота: [[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
Итоговая матрица преобразования: [[6.123233995736766e-17 -1.0 0.0]
 [1.0 6.123233995736766e-17 0.0]
 [-2.5 2.5 1.0]]
------------------------------
------------------------------
Фигура масштабирована в: [Fraction(4, 3), Fraction(2, 3)] раз
Матрица масшиабирования: [[Fraction(4, 3) 0 0]
 [0 Fraction(2, 3) 0]
 [0 0 1]]
Итоговая матрица преобразования: [[8.164311994315688e-17 -0.6666666666666666 0.0]
 [1.3333333333333333 4.082155997157844e-17 0.0]
 [-3.333333333333333 1.666666666666

## Задание 2

### Доказать выпуклость


In [4]:
# Вершины выписывать по часовой стрелке
verts = [[1, 4], [4, 4], [4, 1], [1, 1]]
is_convex = Clipping.is_convex(verts)

Проверка многоугольника на выпуклость
------------------------------
Проверка векторов, образованных точками: [1, 1]-[1, 4] и [1, 4]-[4, 4]
Произведение векторов равно: -1k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [1, 4]-[4, 4] и [4, 4]-[4, 1]
Произведение векторов равно: -1k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [4, 4]-[4, 1] и [4, 1]-[1, 1]
Произведение векторов равно: -1k
Знак произведения веторов: отрицательный
------------------------------
------------------------------
Проверка векторов, образованных точками: [4, 1]-[1, 1] и [1, 1]-[1, 4]
Произведение векторов равно: -1k
Знак произведения веторов: отрицательный
------------------------------
Полигон выпуклый, внутренние нормали ориентированы вправо от его контура


### Найти внутренние нормали

In [5]:
print(f'Внутренние нормали: {Clipping.inner_normals(verts)}')

Поиск внутренних нормалей вектора
------------------------------
Нормаль для ребра из вершин: ([1, 4], [4, 4])
Получившаяся нормаль: (0, 3), обращена внутрь полигона
------------------------------
------------------------------
Нормаль для ребра из вершин: ([4, 4], [4, 1])
Получившаяся нормаль: (3, 0), обращена внутрь полигона
------------------------------
------------------------------
Нормаль для ребра из вершин: ([4, 1], [1, 1])
Получившаяся нормаль: (0, -3), обращена внутрь полигона
------------------------------
------------------------------
Нормаль для ребра из вершин: ([1, 1], [1, 4])
Получившаяся нормаль: (-3, 0), обращена внутрь полигона
------------------------------
Внутренние нормали: [(0, 3), (3, 0), (0, -3), (-3, 0)]


### Если Кирус-Бэк

In [6]:
verts2 = [(2, 3), (4, 5), (7, 2), (4, 1)]
line = [(2, 1), (6, 5)]
print(f'Видимая часть отрезка: {Clipping.cyrus_beck(verts2, line)}')

Рёбра многоугольника: [((2, 3), (4, 5)), ((4, 5), (7, 2)), ((7, 2), (4, 1)), ((4, 1), (2, 3))]
------------------------------
Рассматриваемое ребро: ((2, 3), (4, 5))
Нормаль: (-2, 2)
Отрезок параллелен ребру/выродился в точку, найти параметр t невозможно
------------------------------
Рассматриваемое ребро: ((4, 5), (7, 2))
Нормаль: (3, 3)
Для данного отрезка параметр t равен -3/4
------------------------------
Рассматриваемое ребро: ((7, 2), (4, 1))
Нормаль: (1, -3)
Для данного отрезка параметр t равен 1/4
------------------------------
Рассматриваемое ребро: ((4, 1), (2, 3))
Нормаль: (-2, -2)
Для данного отрезка параметр t равен -1/4
Потенциальные верхние пределы: [Fraction(1, 4), Fraction(-1, 4)]
Потенциальные нижние пределы: [Fraction(-3, 4)]
Выбранный верхний предел: -1/4
Выбранный нижний предел: -3/4
Отрезок частично виден, видимая часть отрезка: [(Fraction(3, 1), Fraction(2, 1)), (Fraction(5, 1), Fraction(4, 1))]
Видимая часть отрезка: [(Fraction(3, 1), Fraction(2, 1)), (Fractio

### Если Коуэн-Сазерленд

In [7]:
verts3 = [(1, 2), (6, 5)]
l1 = [(4, 6), (7, 3)]
l2 = [(0, 0), (7, 1)]
Clipping.cohen_sutherland(verts3, l1)

Код для первой точки линии: 1000
Код для второй точки линии: 0010
------------------------------
Отрезок нуждается в отсекании
Начальная точка лежит вне окна!
Рассматриваемая точка (4, 6) выше окна
Новая начальная точка: (5.0, 5)
------------------------------
------------------------------
Отрезок нуждается в отсекании
Конечная точка лежит вне окна!
Рассматриваемая точка (7, 3) справа от окна
Новая конечная точка: (6, 4.0)
------------------------------
Отсечённая линия лежит внутри окна
Линия отсечена, новые точки: (5.0, 5), (6, 4.0)


[(5.0, 5), (6, 4.0)]

## Задание 3

In [8]:
# Пример входных данных: массив массивов граней 3D
faces = [
    [(0, 0, 0), (0, 2, 0), (0, 0, 2)],
    [(0, 0, 0), (0, 2, 0), (2, 0, 0)],
    [(0, 0, 0), (0, 0, 2), (2, 0, 0)],
    [(0, 2, 0), (0, 0, 2), (2, 0, 0)],
]

faces_matrix = Roberts.generate_faces_matrix(faces)
V = faces_matrix.T
print("Матрица граней объекта:")
print(V)
P = np.array([0,0,1,0])
result = np.dot(P, V)

for index, element in enumerate(result):
    print(f'Граней {index+1}: {element}')

Матрица граней объекта:
[[ 4  0  0  4]
 [ 0  0  4  4]
 [ 0 -4  0  4]
 [ 0  0  0 -8]]
Граней 1: 0
Граней 2: -4
Граней 3: 0
Граней 4: 4
